apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: delivery-control-alert-config
  namespace: monitoring
  labels:
    alertmanagerConfig: main
spec:
  route:
    groupBy: [ app, group, env, team ]
    groupWait: 15s
    groupInterval: 15s
    repeatInterval: 1m
    receiver: Default
    matchers:
      - matchType: =
        name: namespace
        value: monitoring
    routes:
      - receiver: delivery-control-team
        matchers:
        - matchType: =
          name: team
          value: deliveryControl
        - matchType: =
          name: namespace
          value: monitoring
      - receiver: delivery-control-slack
        matchers:
        - matchType: =
          name: namespace
          value: monitoring
        - matchType: =
          name: team
          value: delivery-control-slack
      # - receiver: DeliveryControlAlert 
      #   matchers:
      #   - matchType: =
      #     name: namespace
      #     value: monitoring
  receivers:
    - name: Default
      webhookConfigs: # pode ser webhook, email, slack, teams
        - sendResolved: true
          url: "https://pruu.herokuapp.com/dump/wpwebhook-default"
    - name: delivery-control-team
      webhookConfigs: # pode ser webhook, email, slack, teams
        - sendResolved: true
          url: "https://pruu.herokuapp.com/dump/wpwebhook-delivery-control-team"
    - name: delivery-control-slack
      slackConfigs: # configurações do slack
        - channel: #alertas
          apiURL: # aponta para um dado chave/valor dentro de um secret
            name: slack-secret
            key: SLACK_URL
          sendResolved: true # sinal enviado ao slack dizendo que o alerta foi resolvido
          iconURL: https://avatars3.githubusercontent.com/u/3380462 # icone do prometheus
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.app }}
            {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
              {{" "}}(
              {{- with .CommonLabels.Remove .GroupLabels.Names }}
                {{- range $index, $label := .SortedPairs -}}
                  {{ if $index }}, {{ end }}
                  {{- $label.Name }}="{{ $label.Value -}}"
                {{- end }}
              {{- end -}}
              )
            {{- end }}
          text: >-
            {{ range .Alerts -}}
            *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

            *Summary:* {{ .Annotations.summary }}

            *Description:* {{ .Annotations.description }}

            *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
