apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: delivery-control-alert-config
  namespace: monitoring
  labels:
    alertmanagerConfig: main
spec:
  route:
    groupBy: [ 'alertname' ]
    groupWait: 15s
    groupInterval: 15s
    repeatInterval: 1m
    receiver: Default
    routes:
      - receiver: AlertaDeliveryControl
        match:
          team: delivery-control

  receivers:
    - name: Default
      webhookConfigs: # pode ser webhook, email, slack, teams
        - url: 'https://pruu.herokuapp.com/dump/wpwebhook-default'
    - name: AlertaDeliveryControl
      webhookConfigs: # pode ser webhook, email, slack, teams
      - url: 'https://pruu.herokuapp.com/dump/wpwebhook-delivery-control'
