apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"Alertmanager","metadata":{"annotations":{},"creationTimestamp":"2023-12-07T18:22:32Z","generation":4,"labels":{"app.kubernetes.io/component":"alert-router","app.kubernetes.io/instance":"main","app.kubernetes.io/name":"alertmanager","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"0.26.0"},"name":"main","namespace":"monitoring","resourceVersion":"7922","uid":"9e356b42-f95d-4962-8220-53ec81e79ce7"},"spec":{"image":"quay.io/prometheus/alertmanager:v0.26.0","nodeSelector":{"kubernetes.io/os":"linux"},"podMetadata":{"labels":{"app.kubernetes.io/component":"alert-router","app.kubernetes.io/instance":"main","app.kubernetes.io/name":"alertmanager","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"0.26.0"}},"portName":"web","replicas":2,"resources":{"limits":{"cpu":"100m","memory":"100Mi"},"requests":{"cpu":"4m","memory":"100Mi"}},"retention":"120h","secrets":[],"securityContext":{"fsGroup":2000,"runAsNonRoot":true,"runAsUser":1000},"serviceAccountName":"alertmanager-main","version":"0.26.0"},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2023-12-07T19:20:09Z","message":"","observedGeneration":4,"reason":"","status":"True","type":"Available"},{"lastTransitionTime":"2023-12-07T18:23:35Z","message":"","observedGeneration":4,"reason":"","status":"True","type":"Reconciled"}],"paused":false,"replicas":2,"unavailableReplicas":0,"updatedReplicas":2}}
  creationTimestamp: "2023-12-07T18:22:32Z"
  generation: 6
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.26.0
  name: main
  namespace: monitoring
  resourceVersion: "8037"
  uid: 9e356b42-f95d-4962-8220-53ec81e79ce7
spec:
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: main
  image: quay.io/prometheus/alertmanager:v0.26.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.26.0
  portName: web
  replicas: 2
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 4m
      memory: 100Mi
  retention: 120h
  secrets: []
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: 0.26.0
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-12-07T19:20:09Z"
    message: ""
    observedGeneration: 6
    reason: ""
    status: "True"
    type: Available
  - lastTransitionTime: "2023-12-07T18:23:35Z"
    message: ""
    observedGeneration: 6
    reason: ""
    status: "True"
    type: Reconciled
  paused: false
  replicas: 2
  unavailableReplicas: 0
  updatedReplicas: 2
