apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
  namespace: monitoring
type: Opaque
data:
  SLACK_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA1VERVNUZDNDkvQjA2NlBHQlNKQ0YveWlKZWxORWhuNG5Pb0lVR0FGUElURHgz
# 'https://hooks.slack.com/services/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'