global:
route:
  receiver: Default
  group_by: [ 'alertname' ]
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m

  routes:
    - receiver: AlertaDeliveryControl
      match:
        team: delivery-control

receivers:
  - name: Default
    webhook_configs: # pode ser webhook, email, slack, teams
      - url: 'https://pruu.herokuapp.com/dump/wpwebhook-default'
  - name: AlertaDeliveryControl
    webhook_configs: # pode ser webhook, email, slack, teams
      - url: 'https://pruu.herokuapp.com/dump/wpwebhook-delivery-control'