services:
  delivery-control:
    container_name: delivery-control
    #    image: welissonoliveira/delivery-control:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - delivery-control-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-delivery-control:5432/delivery_control
      SPRING_DATASOURCE_USERNAME: delivery_control
      SPRING_DATASOURCE_PASSWORD: delivery_control
      REDIS_HOST: redis-delivery-control
      REDIS_PORT: 6379
      REDIS_URI: redis-delivery-control:6379
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres
    container_name: postgres-delivery-control
    ports:
      - "5432:5432"
    networks:
      - delivery-control-network
    environment:
      POSTGRES_USER: delivery_control
      POSTGRES_PASSWORD: delivery_control
      POSTGRES_DB: delivery_control
  redis:
    image: redis:5.0-rc
    container_name: redis-delivery-control
    ports:
      - "6379:6379"
    networks:
      - delivery-control-network
networks:
  delivery-control-network:
    name: delivery-control-network
    driver: bridge