global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090

  - job_name: 'delivery-control'
    scrape_interval: 5s
    scrape_timeout: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - delivery-control:8081
          - 172.17.0.1:8081
        labels:
          versao: 1.0
  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets:
          - postgres-exporter:9187
          - 172.17.0.1:9187
    params:
      auth_module: [ foo ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.1:9187