global: # Configurações globais do Prometheus, ou seja, configurações que serão utilizadas em todos os jobs caso não sejam configuradas separadamente dentro de cada job.
  scrape_interval: 15s # Intervalo de coleta dos dados, ou seja, a cada 15 segundos o Prometheus vai até o alvo monitorado coletar as métricas, o padrão é 1 minuto.
  scrape_timeout: 5s # Intervalo para o Prometheus aguardar o alvo monitorado responder antes de considerar que o alvo está indisponível, o padrão é 10 segundos.
  evaluation_interval: 15s # Intervalo para o Prometheus avaliar as regras de alerta, o padrão é 1 minuto.

rule_files: # Inicio da definição das regras de alerta
  - alerts.rules # path do arquivo alert.rules

alerting: # para onde os alertas são enviados
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alert-manager:9093'

scrape_configs: # Inicio da definição das configurações de coleta, ou seja, como o Prometheus vai coletar as métricas e onde ele vai encontrar essas métricas.
  - job_name: 'prometheus' # Nome do job, ou seja, o nome do serviço que o Prometheus vai monitorar.
    static_configs: # Inicio da definição das configurações estáticas, ou seja, configurações que não serão alteradas durante o processo de coleta.
      - targets: # Endereço do alvo monitorado, ou seja, o endereço do serviço que o Prometheus vai monitorar
          - localhost:9090

  - job_name: 'exporter'
    static_configs:
      - targets:
          - exporter:7788

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 172.17.0.1:9100

  - job_name: 'delivery-control'
    scrape_interval: 5s
    scrape_timeout: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - delivery-control:8081
          - 172.17.0.1:8081
        labels:
          versao: 1.0
  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets:
          - postgres-exporter:9187
          - 172.17.0.1:9187
    params:
      auth_module: [ foo ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.1:9187