pipeline {
    agent any

    stages {
        stage('Checkout Source') {
            steps {
                git credentialsId: 'github-ssh', url: 'git@github.com:welisson-oliveira/delivery-control.git', branch: 'main'
            }
        }
        stage('Build Image') {
            steps {
                script {
                    sh 'mvn clean package -DskipTests'
                    dockerapp = docker.build("welissonoliveira/delivery-control:${env.BUILD_ID}", '.')
                }
            }
        }
        // stage('Push image to Dockerhub'){
        //     steps {
        //         script {
        //             docker.withRegistry('https://registry.hub.docker.com/', 'dockerhub') {
        //                 dockerapp.push('latest')
        //                 dockerapp.push("${env.BUILD_ID}")
        //             }
        //         }
        //     }
        // }
        stage('Deploy to Kubernetes') {
            agent{
                kubernetes {
                    cloud 'kind'
                }
            }
            environment {
                tag_version = "${env.BUILD_ID}"
            }
            steps {
                script {
                    sh 'cat ../delivery-control/api/delivery-control-deployment.yml'
                    kubernetesDeploy(configs: '**/k8s/delivery-control/postgres**', kubeconfigId: 'kube')
                    kubernetesDeploy(configs: '**/k8s/delivery-control/redis**', kubeconfigId: 'kube')
                    kubernetesDeploy(configs: '**/k8s/delivery-control/api**', kubeconfigId: 'kube')
                }
            }
        }
    }
}