apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-postgres-policy
spec:
  podSelector:
    matchLabels: 
      app: {{ .Release.Name }}-postgres-deployment
  policyTypes:
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}-api-deployment
      ports:
      - port: 5432
      - protocol: TCP
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}-api-deployment
      ports:
      - port: 5432
      - protocol: TCP