apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-clusterip
spec:
  selector:
    app: {{ .Release.Name }}-postgres-deployment
  ports:
    - port: 5432
      targetPort: 5432