apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  labels:
    name: {{ .Release.Name }}-api-ingress
spec:
  ingressClassName: nginx # verificar o ingressclass disponivel - kubectl get ingressclass
  defaultBackend:
    service: 
      name: {{ .Release.Name }}-api-clusterip
      port: 
        number: 8081
  rules:
  {{- range $host := .Values.api.ingress }}
  - host: 127.0.0.1.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ $.Release.Name }}-api-clusterip
            port: 
              number: 8081
  {{- end -}}