server:
  port: 8081
spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/delivery_control}
    username: ${SPRING_DATASOURCE_USERNAME:delivery_control}
    password: ${SPRING_DATASOURCE_PASSWORD:delivery_control}
    platform: postgres
  jpa:
    hibernate:
      physical-naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    uri: ${REDIS_URI:localhost:6379}
jwt:
  secret: usersecret

# actuator
info:
  app:
    version: @project.version@
    name: @project.name@
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always # exibe todos os detalhes
  endpoints:
    web:
      exposure:
#        include: '*' # exibe todas as informações da JVM e da aplicação (não é muito interessante)
        include: health,info,metrics,prometheus # HEALTH - disponibiliza um endpoint de health-check, INFO - informações da aplicação, METRICS - , PROMETHEUS - expõe metricas para o prometheus
  app:
    name: @project.name@
  # prometheus
  metrics:
    enable:
      jvm: true # habilita metricas da JVM
    export:
      prometheus:
        enabled: true # habilita o export das metricas para o prometheus
    distribution:
      slo:
        http:
          server:
            requests: 50ms,100ms,200ms,300ms,500ms,1s # metrica expecifica à SLO Obs: SLA esta deprecated
    tags:
      application: @project.name@ # configuração de taguiamento, para identificar a aplicação


# liquibase
url: jdbc:postgresql://localhost:5432/delivery_control
username: delivery_control
password: delivery_control
driver: org.postgresql.Driver
referenceUrl: hibernate:spring:br.com.acert.deliverycontrol.domain?dialect=org.hibernate.dialect.PostgreSQLDialect
#changeLogFile: src/main/resources/db/changelog/changelog-master.yaml
outputChangeLogFile: src/main/resources/db/changelog/new-changelog-master.yaml
diffChangeLogFile: src/main/resources/db/changelog/liquibase-diff-changeLog.yaml