spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicity-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: org.firebirdsql.jdbc.FBDriver
    url: jdbc:firebirdsql://localhost:3050/delivery_control.fdb
    username: delivery_control
    password: delivery_control
    platform: firebird

#liquibase
#url: jdbc:firebirdsql://localhost:3050/delivery_control.fdb
#username: delivery_control
#password: delivery_control
#driver: org.firebirdsql.jdbc.FBDriver
#referenceUrl: hibernate:spring:com.acert.deliverycontrol.domain?dialect=org.firebirdsql.jdbc.FBDriver
#changeLogFile: src/main/resources/db/changelog/generated-changelog-master.xml
#diffChangeLogFile: src/main/resources/db/changelog/liquibase-diff-changeLog.xml