version: "3.7"
services:
  postgres-delivery-control:
    image: postgres
    container_name: postgres-delivery-control
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: delivery_control
      POSTGRES_PASSWORD: delivery_control
      POSTGRES_DB: delivery_control
  redis:
    image: redis:5.0-rc
    container_name: redis-delivery-control
    ports:
      - 6379:6379