apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"Alertmanager","metadata":{"annotations":{},"creationTimestamp":"2023-10-23T22:22:26Z","generation":1,"labels":{"app.kubernetes.io/component":"alert-router","app.kubernetes.io/instance":"main","app.kubernetes.io/name":"alertmanager","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"0.26.0"},"name":"main","namespace":"monitoring","resourceVersion":"660830","uid":"0c321a0b-7159-4d2f-a6ac-521c49e59e48"},"spec":{"alertmanagerConfigSelector":{"matchLabels":{"alertmanagerConfig":"main"}},"image":"quay.io/prometheus/alertmanager:v0.26.0","nodeSelector":{"kubernetes.io/os":"linux"},"podMetadata":{"labels":{"app.kubernetes.io/component":"alert-router","app.kubernetes.io/instance":"main","app.kubernetes.io/name":"alertmanager","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"0.26.0"}},"portName":"web","replicas":3,"resources":{"limits":{"cpu":"100m","memory":"100Mi"},"requests":{"cpu":"4m","memory":"100Mi"}},"retention":"120h","secrets":[],"securityContext":{"fsGroup":2000,"runAsNonRoot":true,"runAsUser":1000},"serviceAccountName":"alertmanager-main","version":"0.26.0"},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2023-11-06T15:33:24Z","observedGeneration":1,"status":"True","type":"Available"},{"lastTransitionTime":"2023-11-06T15:32:52Z","observedGeneration":1,"status":"True","type":"Reconciled"}],"paused":false,"replicas":3,"unavailableReplicas":0,"updatedReplicas":3}}
  creationTimestamp: "2023-10-23T22:22:26Z"
  generation: 2
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.26.0
  name: main
  namespace: monitoring
  resourceVersion: "793706"
  uid: 0c321a0b-7159-4d2f-a6ac-521c49e59e48
spec:
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: main
  image: quay.io/prometheus/alertmanager:v0.26.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.26.0
  portName: web
  replicas: 3
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 4m
      memory: 100Mi
  retention: 120h
  secrets: []
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: 0.26.0
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2023-11-06T15:33:24Z"
    observedGeneration: 2
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-06T15:32:52Z"
    observedGeneration: 2
    status: "True"
    type: Reconciled
  paused: false
  replicas: 3
  unavailableReplicas: 0
  updatedReplicas: 3
