apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: delivery-control-podmonitor
  labels:
    app: delivery-control-pod
spec:
  namespaceSelector: # seletor de namespaces
    matchNames: # namespaces que serão monitorados
      - default # namespace que será monitorado
  selector: # seletor para identificar os pods que serão monitorados
    matchLabels: # labels que identificam os pods que serão monitorados
      app: delivery-control-deployment
  podMetricsEndpoints: # endpoints que serão monitorados
    - interval: 10s # intervalo de tempo entre as requisições
      path: /actuator/prometheus # caminho para a requisição
      targetPort: 8081 # porta do target