apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-role-bind
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-api-user
  namespace: default
roleRef:
  kind: Role
  name: {{ .Release.Name }}-api-role
  apiGroup: rbac.authorization.k8s.io