INSERT INTO CUSTOMER_ORDER
(ID, DESCRIPTION, STATUS, ORDER_DATE, CLIENT_ID)
VALUES(nextval('order_seq'), 'CREATED', 'CREATED', TIMESTAMP '2023-08-05 12:34:56', 1);

INSERT INTO CUSTOMER_ORDER
(ID, DESCRIPTION, STATUS, ORDER_DATE, CLIENT_ID)
VALUES(nextval('order_seq'), 'IN_PROGRESS', 'IN_PROGRESS', TIMESTAMP '2023-08-05 12:34:56', 1);

INSERT INTO CUSTOMER_ORDER
(ID, DESCRIPTION, STATUS, ORDER_DATE, CLIENT_ID)
VALUES(nextval('order_seq'), 'WAITING', 'WAITING', TIMESTAMP '2023-08-05 12:34:56', 1);

INSERT INTO CUSTOMER_ORDER
(ID, DESCRIPTION, STATUS, ORDER_DATE, CLIENT_ID)
VALUES(nextval('order_seq'), 'CANCELED', 'CANCELED', TIMESTAMP '2023-08-05 12:34:56', 1);

INSERT INTO CUSTOMER_ORDER
(ID, DESCRIPTION, STATUS, ORDER_DATE, CLIENT_ID)
VALUES(nextval('order_seq'), 'DONE', 'DONE', TIMESTAMP '2023-08-05 12:34:56', 1);