apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delivery-control-bind
subjects:
- kind: ServiceAccount
  name: delivery-control-user
  namespace: default
roleRef:
  kind: Role
  name: delivery-control-role
  apiGroup: rbac.authorization.k8s.io