apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delivery-control-role
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - services
    verbs:
      - get
      - list
      - watch