apiVersion: v1
kind: LimitRange
metadata:
  name: container-limit-range
spec:
  limits:
    - max:
        cpu: "1000m"
        memory: 2100Mi
      min:
        cpu: "150m"
        memory: 100Mi
      default:
        cpu: "250m"
        memory: "128Mi"
      defaultRequest:
        cpu: "150m"
        memory: "110Mi"
      type: Container