apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: ZGVsaXZlcnlfY29udHJvbA==
  POSTGRES_PASSWORD: ZGVsaXZlcnlfY29udHJvbA==
  POSTGRES_DB: ZGVsaXZlcnlfY29udHJvbA==
